### ISSUE TITLE
ox_lib context menu persisting through apartment exit (and logout)

### ISSUE THREAD

**Issue by davicustv** [Qbox-project/qb-apartments#5]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Enter apartment using context menu
2. Exit apartment using context menu
3. Leave the range of the apartment enterance
4. ERROR - Context menu for exiting apartment will still open when you press 'E' despite not being inside the apartment still. 

**Expected behavior**
Pressing 'E' when not in range of the apartment exit should not bring up the context menu.

**Screenshots**
https://streamable.com/kc7zoh

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones? This was produced on a fresh install of Qbox from recipe.
 - Have you renamed `qb-` to something custom? no

**Additional context**
This will exist across characters, as well. If you exit apartment, log out, and select a new character, then pressing 'E' will bring up the context menu as well. Restarting the resource will fix this issue.

**Comment by Rav3n95** [comment]
I'll have a look tomorrow, it's something I messed up. Thanks for the report!
